# Generated by Django 4.1.7 on 2023-02-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='Описание')),
                ('image', models.CharField(max_length=200, verbose_name='Фото')),
                ('category', models.CharField(choices=[('PHONE', 'Телефон'), ('LAPTOP', 'Ноутбук'), ('CAMERA', 'Фотокамера'), ('OTHER', 'Другое')], default='OTHER', max_length=50, verbose_name='Категория')),
                ('rest', models.IntegerField(verbose_name='Остаток')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость')),
            ],
        ),
    ]
