# Generated by Django 4.1.7 on 2023-03-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cart_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
    ]
