# Generated by Django 4.1.7 on 2023-03-14 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_cart_ordered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
