# Generated by Django 4.1.7 on 2023-03-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_cart_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(related_name='order', to='store.product'),
        ),
    ]
